# Generated by Django 4.1.5 on 2023-01-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_vacanciesnumberanalyze_number2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacanciesnumberanalyze',
            options={'verbose_name': 'Статистику за год', 'verbose_name_plural': 'Динамика количества вакансий по годам'},
        ),
        migrations.AlterField(
            model_name='vacanciesnumberanalyze',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Количество вакансий'),
        ),
        migrations.AlterField(
            model_name='vacanciesnumberanalyze',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год'),
        ),
    ]
