# Generated by Django 4.1.5 on 2023-01-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vacanciesnumberanalyze_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesSalaryAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('number', models.PositiveIntegerField(verbose_name='Средняя зарплата')),
                ('number_by_job', models.PositiveIntegerField(verbose_name='Средняя зарплата для Devops')),
            ],
            options={
                'verbose_name': 'Статистика за год',
                'verbose_name_plural': 'Динамика уровня зарплат по годам',
            },
        ),
    ]
