# Generated by Django 4.1.5 on 2023-01-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vacanciessalaryanalyze'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacanciessalaryanalyze',
            old_name='number',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='vacanciessalaryanalyze',
            old_name='number_by_job',
            new_name='salary_by_job',
        ),
    ]
