# Generated by Django 4.1.5 on 2023-01-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_number_vacanciessalaryanalyze_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('skills', models.TextField(verbose_name='Топ-10 навыков')),
            ],
            options={
                'verbose_name': 'Статистика за год',
                'verbose_name_plural': 'Динамика самых встречаемых навыков по годам',
            },
        ),
    ]
