# Generated by Django 4.1.5 on 2023-01-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skillsanalyze'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaNumberAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(verbose_name='Название города')),
                ('stake', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Доля')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Динамика количества вакансий по городам',
            },
        ),
        migrations.CreateModel(
            name='AreaSalaryAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(verbose_name='Название города')),
                ('salary', models.PositiveIntegerField(verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Динамика уровня зарплат по городам',
            },
        ),
    ]
